travelnet/map/urls.py
from django.urls import path

from .views import PostsView

app_name = 'map'

urlpatterns = [
    path('posts/', PostsView.as_view(), name="posts")
]

travelnet/publications/urls.py
from django.urls import path
from .views import PublicationList, CreatePublicationView, DetailedPublicationView, edit_publication

app_name = 'publications'
urlpatterns = [
    path('', PublicationList.as_view(), name='publication_list'),
    path('create/', CreatePublicationView.as_view(), name='create_publication'),
    path('<int:pk>/', DetailedPublicationView.as_view(), name='detail_publication'),
    path('edit/<int:pk>/', edit_publication, name="edit_publication")
]

travelnet/travelnet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from rating import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),

    path('map/', include('map.urls')),
    path('publications/', include('publications.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('homepage.urls')),
    path('about/', include('about.urls')),

    # TODO: убрать это отсюда
    path('api/v1/likes', views.PublicationLikeViews.as_view()),
    path('api/v1/comments', views.CommentViews.as_view()),
    path('api/v1/comment-likes', views.CommentLikeViews.as_view()),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travelnet/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView, PasswordChangeView, PasswordChangeDoneView, \
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from .forms import LoginForm
from .views import signup, profile, user_detail

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html', authentication_form=LoginForm),
        name='login'),
    path('password_change/',
         PasswordChangeView.as_view(template_name='users/password_change.html'),
         name='password_change'),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/',
         PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('signup/', signup, name="signup"),
    path('edit/profile/', profile, name="profile"),
    path('user_detail/<int:user_id>', user_detail, name="user_detail"),
]

travelnet/users/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
from sorl.thumbnail import get_thumbnail


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """

    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    username = models.CharField(_('username'), unique=True, max_length=30)
    email = models.EmailField(_('email address'), unique=True)
    image = models.ImageField(_('аватар'), upload_to='uploads/', null=True, blank=True)

    # follows = models.ManyToManyField('self', verbose_name=_('Подписки'), symmetrical=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = CustomUserManager()

    def get_image_200x200(self):
        return get_thumbnail(self.image, '200x200', crop='center', quality=51)

    def get_image_300x300(self):
        return get_thumbnail(self.image, '300x300', crop='center', quality=51)

    def image_tmb(self):
        if self.image:
            return mark_safe(
                f'<img src="{self.image.url}" width="50">'
            )
        return 'Нет изображения'

    image_tmb.short_description = 'превью'
    image_tmb.allow_tags = True

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        db_table = "user"

    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    birthday = models.DateField("День рождения", null=True, blank=True, help_text="Ваш день рождения")

    class Meta:
        verbose_name = "День рождения"
        verbose_name_plural = "Дни рождения"

    def __str__(self):
        return f'{self.user.username}'


@receiver(post_save, sender=CustomUser)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        # if instance.image.name is None:
        #     instance.image = requests.get('https://thiscatdoesnotexist.com')
        #     instance.save()
        Profile.objects.create(user=instance)

    instance.profile.save()

travelnet/users/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth import get_user_model, forms as auth_forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from .models import Profile


class SignupForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя', max_length=255, help_text='Обязательно',
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': ''}))
    email = forms.EmailField(max_length=200, help_text='Обязательно',
                             widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': ''}))
    password1 = forms.CharField(label=_("Password"),
                                widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': ''}))
    password2 = forms.CharField(label=_("Password confirmation"),
                                widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': ''}),
                                help_text=_("Повторите пароль"))

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': ''})}


class UserDataForm(forms.ModelForm):
    remove_photo = forms.BooleanField(label="Удалить фото", required=False, initial=False)
    image = forms.ImageField(label='Аватар', required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if visible.widget_type == 'checkbox':
                visible.field.widget.attrs['class'] = 'form-check-control'
            else:
                visible.field.widget.attrs['class'] = 'form-control'

    def clean(self):
        email = self.cleaned_data.get('email')
        if get_user_model().objects.filter(email=email).exclude(pk=self.instance.pk):
            raise ValidationError("Пользователь с такой почтой уже сущестсвует")
        return self.cleaned_data

    def save(self, commit=True):
        instance = super(UserDataForm, self).save(commit=False)
        if self.cleaned_data.get('remove_photo'):
            instance.image.delete(save=False)
        if commit:
            instance.save()
        return instance

    class Meta:
        model = get_user_model()
        fields = [
            'email',
            'first_name',
            'last_name',
            'image'
        ]
        labels = {
            "email": "Email",
            "first_name": "Имя",
            "last_name": "Фамилия",
            "image": "Аватар"
        }


class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control col-2 w-auto ms-3'

    class Meta:
        model = Profile
        fields = ['birthday']
        labels = {'birthday': "Дата рождения"}
        widgets = {'birthday': forms.SelectDateWidget(years=[i for i in range(1901, datetime.now().year)])}


class UserCreationForm(auth_forms.UserCreationForm):
    class Meta(auth_forms.UserCreationForm.Meta):
        model = get_user_model()
        fields = ("username", "email")


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': ''}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': '',
            'id': 'hi',
        }
    ))

travelnet/users/views.py
from django.contrib.auth import get_user_model, login
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import SignupForm, UserDataForm, ProfileForm


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = get_user_model().objects.create_user(password=raw_password, username=username, email=email)
            # why authenticate() when we just created the user?
            # user = authenticate(email=email, password=raw_password)
            login(request, user)
            return redirect(reverse('homepage:home'))
    else:
        form = SignupForm()
    return render(request, "users/signup.html", {'form': form})


@login_required
def profile(request):
    user = request.user
    if request.method == 'POST':
        data_form = UserDataForm(request.POST, request.FILES, instance=request.user)
        profile_form = ProfileForm(request.POST)
        if data_form.is_valid() and profile_form.is_valid():
            data_form.save()
            user.profile.birthday = profile_form.cleaned_data["birthday"]
            user.save()
            return redirect(reverse('users:profile'))
    else:
        data_form = UserDataForm(initial={"email": user.email, "first_name": user.first_name,
                                          "last_name": user.last_name, "remove_photo": False})
        profile_form = ProfileForm(initial={"birthday": user.profile.birthday})
    context = {
        "data_form": data_form,
        "profile_form": profile_form
    }
    return render(request, "users/profile.html", context)


def user_detail(request, user_id):
    if user_id == 0:
        return redirect(reverse('users:user_detail', kwargs={'user_id': request.user.pk}))
    user = get_user_model().objects.get(pk=user_id)

    publication_set = user.publication_set.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(publication_set, 5)
    try:
        publications = paginator.page(page)
    except PageNotAnInteger:
        publications = paginator.page(1)
    except EmptyPage:
        publications = paginator.page(paginator.num_pages)
    context = {
        'user': user,
        'current_user': request.user,
        'publications': publications,
    }
    return render(request, "users/user_detail.html", context)

travelnet/templates/users/logged_out.html
{% extends "base.html" %}
{% block content %}
    <p>Вы вышли из аккаунта</p>
{% endblock %}

travelnet/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
    <p><span class="h1">Вход</span> <span class="h4 text-secondary fw-normal">Впервые здесь? <a
            href="{% url 'users:signup' %}">Регистрация</a></span></p>
    <div class="row text-left">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    {{ error|escape }}
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                {{ error|escape }}
            {% endfor %}
        {% endif %}

        <form method="post" class="pe-4" action="">
            {% csrf_token %}

            {% for field in form %}
                <label for="{{ field.id_for_label }}" class="col-lg-4 col-sm-12">
                    {{ field.label }}
                    {% if field.field.required %}
                        <span>*</span>
                    {% endif %}
                </label>
                {{ field }}
                {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help">
                        {{ field.help_text|safe }}
                    </small>
                {% endif %}
                <br>

            {% endfor %}

            <button type="submit" class="btn btn-outline-primary">Войти</button>
            <a class="float-end" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
        </form>
    </div>
{% endblock %}

travelnet/templates/users/password_change.html
{% extends "base.html" %}
{% block content %}
    {% include "includes/base_save_form.html" %}
{% endblock %}

travelnet/templates/users/password_change_done.html
{% extends "base.html" %}
{% block content %}
    <p>Вы успешно сменили пароль</p>
{% endblock %}

travelnet/templates/users/password_reset.html
{% extends "base.html" %}
{% block content %}
    {% include "includes/base_save_form.html" %}
{% endblock %}

travelnet/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
    <p>Ваш пароль успешно восстановлен</p>
{% endblock %}

travelnet/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block content %}
    {% include "includes/base_save_form.html" %}
{% endblock %}

travelnet/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block content %}
    <p>Ссылка для сброса пароля отправлена на вашу почту</p>
{% endblock %}

travelnet/templates/users/profile.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-4">
            <h1>Мой профиль</h1>
            <form class="row" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-12">
                    {{ data_form.email.errors }}
                    {{ data_form.email.label_tag }}
                    {{ data_form.email }}
                </div>
                <div class="w-100"></div>
                <div class="col-6">
                    {{ data_form.first_name.errors }}
                    {{ data_form.first_name.label_tag }}
                    {{ data_form.first_name }}
                </div>
                <div class="col-6">
                    {{ data_form.last_name.errors }}
                    {{ data_form.last_name.label_tag }}
                    {{ data_form.last_name }}
                </div>
                <div class="w-100 pb-2"></div>
                <div class="w-auto row">
                    {{ profile_form.birthday.errors }}
                    {{ profile_form.birthday.label_tag }}
                    {{ profile_form.birthday }}
                </div>

                <div class="w-100 pb-2"></div>

                {% if user.image %}
                    <div class="col-9 pb-3">
                        <p class="mb-0 pb-1">Ваш аватар</p>
                        <img class="" src="/media/{{ user.get_image_200x200 }}" alt="user's profile picture">
                        <div class="">
                            {{ data_form.remove_photo.errors }}
                            {{ data_form.remove_photo.label_tag }}
                            {{ data_form.remove_photo }}
                        </div>
                    </div>
                {% else %}
                    <div class="col-12 pb-3">
                        <p>Нет изображения</p>
                        {{ data_form.image.errors }}
                        {{ data_form.image.label_tag }}
                        {{ data_form.image }}
                    </div>
                {% endif %}
                <div class="w-100"></div>
                <div class="col-12">
                    <button type="submit" class="float-start col-4 btn btn-primary">Сохранить</button>
                    <a class="btn-danger btn ms-1 col-4 float-end" href="{% url 'users:logout' %}">Выйти</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

travelnet/templates/users/signup.html
{% extends "base.html" %}
{% block title %}
    Регистрация
{% endblock %}
{% block content %}
    <p><span class="h1">Регистрация</span> <span class="h4 fw-normal text-secondary">Уже есть аккаунт? <a
            href="{% url 'users:login' %}">Войти</a></span></p>
    <form action="" method="post" class="pe-4">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Зарегистрироваться</button>
    </form>
{% endblock %}

travelnet/templates/users/user_detail.html
{% extends 'base.html' %}

{% block title %}
    Информация о пользователе
{% endblock %}

{% block content %}
    <h1 class="username">{{ user.username }}</h1>
    {% if user.image %}
        <div class="avatar"><img src="/media/{{ user.get_image_200x200 }}"></div>
        <div class="user-info">
    {% else %}
        <div class="user-info">
        <h3 class="user-info">Аватар отсутствует</h3>
    {% endif %}
<h3 class="user-info">Имя: {{ user.first_name|default:"Не указано" }}</h3>
<h3 class="user-info">Фамилия: {{ user.last_name|default:"Не указано" }}</h3>
<h3 class="user-info">День рождения: {{ user.profile.birthday|default:"Не указано" }}</h3>
{% if current_user.id == user.id %}
    <h3><a href="{% url 'users:profile' %}">Редактировать</a></h3>
{% endif %}
</div>
{% if current_user.id == user.id %}
    <h2>Мои публикации <a href="{% url 'publications:create_publication' %}"
                          class="text-success fw-semibold">Создать</a></h2>
{% else %}
    <h2>Публикации пользователя {{ user.username }}</h2>
{% endif %}

<div class="infinite-container">
    {% for post in publications %}
        <div class="infinite-item">{% include "includes/publication.html" %}</div>
        {% empty %}
        <p>Вау, тут пусто...</p>
    {% endfor %}
</div>

<div class="d-flex justify-content-center" style="display: none;">
    <div class="loading spinner-border text-primary" role="status"></div>
</div>

{% if publications.has_next %}
    <a class="infinite-more-link" href="?page={{ publications.next_page_number }}">More</a>
{% endif %}
<script>
    var infinite = new Waypoint.Infinite({
        element: $('.infinite-container')[0],
        onBeforePageLoad: function () {
            $('.loading').show();
        },
        onAfterPageLoad: function ($items) {
            $('.loading').hide();
        }
    });
</script>
{% endblock %}