travelnet/about/urls.py
from django.urls import path

from .views import description, faq

app_name = 'about'
urlpatterns = [
    path('', description, name="description"),
    path('faq/', faq, name="faq")
]

travelnet/homepage/urls.py
from django.urls import path

from .views import feed

app_name = 'homepage'
urlpatterns = [
    path('', feed, name="home"),
]

travelnet/map/urls.py
from django.urls import path

from .views import PostsView

app_name = 'map'

urlpatterns = [
    path('posts/', PostsView.as_view(), name="posts")
]

travelnet/publications/urls.py
from django.urls import path
from .views import PublicationList, CreatePublicationView, DetailedPublicationView, edit_publication

app_name = 'publications'
urlpatterns = [
    path('', PublicationList.as_view(), name='publication_list'),
    path('create/', CreatePublicationView.as_view(), name='create_publication'),
    path('<int:pk>/', DetailedPublicationView.as_view(), name='detail_publication'),
    path('edit/<int:pk>/', edit_publication, name="edit_publication")
]

travelnet/travelnet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from rating import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),

    path('map/', include('map.urls')),
    path('publications/', include('publications.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('homepage.urls')),
    path('about/', include('about.urls')),

    # TODO: убрать это отсюда
    path('api/v1/likes', views.PublicationLikeViews.as_view()),
    path('api/v1/comments', views.CommentViews.as_view()),
    path('api/v1/comment-likes', views.CommentLikeViews.as_view()),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travelnet/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView, PasswordChangeView, PasswordChangeDoneView, \
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from .forms import LoginForm
from .views import signup, profile, user_detail

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html', authentication_form=LoginForm),
        name='login'),
    path('password_change/',
         PasswordChangeView.as_view(template_name='users/password_change.html'),
         name='password_change'),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/',
         PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('signup/', signup, name="signup"),
    path('edit/profile/', profile, name="profile"),
    path('user_detail/<int:user_id>', user_detail, name="user_detail"),
]

travelnet/publications/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from mapbox_location_field.models import LocationField

from core.mixins import AuthorMixin, DatetimeCreatedMixin, VisibleMixin
from .managers import PublicationManager


# TODO: move these mixins to a separate file


class Publication(AuthorMixin, DatetimeCreatedMixin, VisibleMixin):
    text = models.TextField('Текст')
    location = LocationField("Расположение", map_attrs={
        "placeholder": "Выберите геопозицию на карте", "zoom": 7,
        "language": "ru",
        "center": [37.60024739728942, 55.763870740960954]
    })

    objects = PublicationManager()

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

    def __str__(self):
        return f'{self.author} in {self.location}'


class Attachment(DatetimeCreatedMixin, AuthorMixin):
    class AttachmentType(models.TextChoices):
        PHOTO = "Photo", _("Фото")
        VIDEO = "Video", _("Видео")

    file = models.ImageField('Приложение', upload_to='attachments/')
    file_type = models.CharField('Тип файла', choices=AttachmentType.choices, max_length=10)

    publication = models.ForeignKey(Publication, on_delete=models.CASCADE, verbose_name='Публикация')

    class Meta:
        verbose_name = 'Вложение'
        verbose_name_plural = 'Вложения'

travelnet/publications/forms.py
from django import forms
from mapbox_location_field.forms import LocationField

from .models import Publication


# allows for custom error message
class BetterLocationFormField(LocationField):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.error_messages = {'required': 'Пожалуйста, укажите локацию, это обязательно.'}


class CreatePublicationForm(forms.ModelForm):
    text = forms.CharField(label='Текст', widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Сегодня я побывал в пабе на старом арбате..'
    }))

    author = forms.HiddenInput()

    file = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'multiple': True, 'class': 'form-control'}),
        label='Вложения (можно выбрать несколько фото)', required=False
    )

    location = BetterLocationFormField(error_messages={'required': 'asdfaskldjfhasdlkjflkajsdf'}, map_attrs={
        "placeholder": "Выберите геопозицию на карте", "zoom": 7,
        "language": "ru",
        "center": [37.60024739728942, 55.763870740960954]
    })

    class Meta:
        model = Publication
        fields = ('location', 'text')
        error_messages = {
            'location': {
                'required': ("This writer's name is too long."),
            },
        }

travelnet/publications/views.py
import datetime

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from publications.forms import CreatePublicationForm
from publications.models import Publication, Attachment


class PublicationList(ListView):
    model = Publication
    template_name = 'publications/publication_list.html'
    context_object_name = 'publications'

    def get_queryset(self):
        datetime_most_popular_created_before = datetime.datetime.now() - datetime.timedelta(days=14)

        # если чел разлогинен или у него 0 подписок, кидаем популярные посты
        # иначе кидаем посты из подписок
        q2 = Publication.objects.popular_posts(datetime_created_after=datetime_most_popular_created_before)

        if not self.request.user.is_authenticated or self.request.user.follows.count() == 0:
            return q2
        q1 = Publication.objects.user_feed(self.request.user)
        res = (q1 & q2).distinct()
        return res

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        object_list = context['object_list']
        page = self.request.GET.get('page', 1)
        paginator = Paginator(object_list, 5)
        try:
            numbers = paginator.page(page)
        except PageNotAnInteger:
            numbers = paginator.page(1)
        except EmptyPage:
            numbers = paginator.page(paginator.num_pages)

        context['publications'] = numbers

        context['new_publication_form'] = CreatePublicationForm()
        return context


class DetailedPublicationView(DetailView):
    model = Publication
    template_name = 'publications/publication_detail.html'
    context_object_name = 'post'

    queryset = Publication.objects.get_queryset().select_and_prefetch()


class CreatePublicationView(CreateView):
    model = Publication
    template_name = 'publications/create_publication.html'
    form_class = CreatePublicationForm
    success_url = reverse_lazy('publications:publication_list')
    object = None

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        publication = form.save(commit=False)
        publication.author = self.request.user
        publication.save()

        files = self.request.FILES.getlist('file')
        if form.is_valid():
            for f in files:
                Attachment.objects.create(
                    author=self.request.user, publication_id=publication.id, file_type='Photo', file=f
                )

        return super().form_valid(form)


def edit_publication(request, pk):
    template = 'publications/edit_publication.html'
    publication = Publication.objects.get(pk=pk)
    if request.method == 'POST':
        form = CreatePublicationForm(request.POST, request.FILES, instance=publication)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('publications:detail_publication', kwargs={'pk': pk}))

    else:
        form = CreatePublicationForm(instance=publication)
        files = request.FILES.getlist('file')
        for f in files:
            Attachment.objects.create(
                author=request.user, publication_id=pk, file_type='Photo', file=f
            )
        return render(request, template, context={'form': form})

travelnet/templates/includes/base_save_form.html
<html>
<form method="post" action="">

    {% csrf_token %}

    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
</html>

travelnet/templates/includes/create_publication.html
{% load thumbnail %}
{% load static %}

<form enctype="multipart/form-data" action="{% url 'publications:create_publication' %}" method="post"
      class="container-lg publication">
    {% csrf_token %}
    <div class="post-header">
        <div class="publication-avatar">
            {% if user.image %}
                {% thumbnail user.image "50x50" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
                         alt="{{ user }}'s profile picture">
                {% endthumbnail %}
            {% endif %}
        </div>
        <h4 class="username"><a href="{% url 'users:user_detail' user_id=user.id %}">{{ user.username }}</a></h4><br>
        <p class="text-muted">Еще не опубликовано!</p>
    </div>

    <div class="location">
        {{ form.location.errors }}
        {{ form.location.label_tag }}
        {{ form.location }}
    </div>
    <br>
    <div class="post-main">
        {{ form.text.errors }}
        {{ form.text.label_tag }}
        {{ form.text }}
    </div>
    <br>
    <div class="row px-4 pb-3">
        {{ form.file.errors }}
        {{ form.file.label_tag }}
        {{ form.file }}
        <small class="text-muted">Добавьте фото к посту, чтобы он мог отображаться на карте популярных постов</small>
    </div>

    <div class="post-footer row px-3">
        <div class="d-flex justify-content-center mb-1">
            <input type="submit" value="Опубликовать!" class=" col-7 btn btn-success publish-button">
        </div>
    </div>

    {{ form.media }}
</form>

travelnet/templates/includes/edit_publication.html
{% load thumbnail %}
{% load static %}

<form enctype="multipart/form-data" action="" method="post" class="container-lg publication">
    {% csrf_token %}
    <div class="post-header">
        <div class="publication-avatar">
            {% if user.image %}
                {% thumbnail user.image "50x50" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
                         alt="{{ user }}'s profile picture">
                {% endthumbnail %}
            {% endif %}
        </div>
        <h4 class="username"><a href="{% url 'users:user_detail' user_id=user.id %}">{{ user.username }}</a></h4><br>
        <p class="text-muted">Редактируется</p>
    </div>

    <div class="location">
        {{ form.location.errors }}
        {{ form.location.label_tag }}
        {{ form.location }}
    </div>
    <br>
    <div class="post-main">
        {{ form.text.errors }}
        {{ form.text.label_tag }}
        {{ form.text }}
    </div>
    <br>
    <div class="row px-4 pb-3">
        {{ form.file.errors }}
        {{ form.file.label_tag }}
        {{ form.file }}
        <small class="text-muted">Добавьте фото к посту, чтобы он мог отображаться на карте популярных постов</small>
    </div>

    <div class="post-footer row px-3">
        <div class="d-flex justify-content-center mb-1">
            <input type="submit" value="Опубликовать!" class=" col-7 btn btn-success publish-button">
        </div>
    </div>

    {{ form.media }}
</form>

travelnet/templates/includes/footer.html
<div class="footer">
    <p>travel_net © 2022</p>
</div>

travelnet/templates/includes/header.html
<h2> Меню </h2>
<a href="{% url 'homepage:home' %}">
    <i class="fa fa-user-o" aria-hidden="true"></i>
    Главная
</a>
<a href="{% url 'map:posts' %}">
    <i class="fa fa-clone" aria-hidden="true"></i>
    Карта
</a>
{% if user.is_authenticated %}
    <a href="{% url 'users:user_detail' user_id=user.id %}">
        <i class="fa fa-star-o" aria-hidden="true"></i>
        Профиль
    </a>
    <a href="{% url 'users:logout' %}">
        <i class="fa fa-star-o" aria-hidden="true"></i>
        Выйти
    </a>
{% else %}
    <a href="{% url 'users:login' %}">
        <i class="fa fa-star-o" aria-hidden="true"></i>
        Войти
    </a>
{% endif %}
<a href="{% url 'about:description' %}">
    <i class="fa fa-trash-o" aria-hidden="true"></i>
    Помощь
</a>

travelnet/templates/includes/header_mobile.html
<div class="top-nav">
    <div>
        <h2>Travel.Net</h2>
    </div>
    <input id="menu-toggle" type="checkbox"/>
    <label class='menu-button-container' for="menu-toggle">
        <div class='menu-button'></div>
    </label>
    <ul class="menu">
        <li>
            <a href="{% url 'homepage:home' %}">
                <i class="fa fa-user-o" aria-hidden="true"></i>
                Главная
            </a>
        </li>
        <li>
            <a href="{% url 'map:posts' %}">
                <i class="fa fa-clone" aria-hidden="true"></i>
                Карта
            </a>
        </li>

        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'users:user_detail' user_id=user.id %}">
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                    Профиль
                </a>
            </li>
            <li>
                <a href="{% url 'users:logout' %}">
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                    Выйти
                </a>
            </li>
        {% else %}
            <li>
                <a href="{% url 'users:login' %}">
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                    Войти
                </a>
            </li>
        {% endif %}
        <li>
            <a href="{% url 'about:description' %}">
                <i class="fa fa-trash-o" aria-hidden="true"></i>
                Помощь
            </a>
        </li>
    </ul>
</div>

travelnet/templates/includes/navigation.html
<aside class="desktop-menu">
    {% include "includes/header.html" %}
    {% include "includes/footer.html" %}
</aside>

travelnet/templates/includes/publication.html
{% load thumbnail %}
{% load static %}

<div class="container-lg publication">
    <div class="post-header">
        <div class="publication-avatar">
            {% if post.author.image %}
            {% thumbnail post.author.image "50x50" crop="center" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
                 alt="{{ post.author }}'s profile picture">
            {% endthumbnail %}
            {% else %}
            {# TODO: standard user pfp #}
            {% endif %}
        </div>
        <h4 class="username"><a
                href="{% url 'users:user_detail' user_id=post.author.id %}">{{ post.author.username }}</a></h4><br>
        <p class="text-muted">Опубликовано {{ post.datetime_created }}</p>
        {% if post.author.id == user.id %}
            <a href="{% url 'publications:edit_publication' pk=post.id %}" class="float-end">Редактировать пост</a><br>
        {% endif %}
    </div>

    <div class="location">
        {# <img class="point" src="{% static 'img/other/point.png' %}">#}
        <a target="_blank" href="https://maps.yandex.ru/?text={{ post.location.1 }}+{{ post.location.0 }}">Открыть на
            Яндекс.Картах</a>
        <a href="{% url 'publications:detail_publication' pk=post.id %}" class="float-end">Открыть пост</a>
    </div>
    <br>

    <div class="post-main">
        <span value="{{ post.id }}" hidden></span>
        <p class="">{{ post.text }}</p>
    </div>

    {% for attachment in post.attachment_set.all %}
    <div class="attachments container mb-5 text-center">
        {% if attachment.file_type == "Photo" %}
        <img src="{{ attachment.file.url }}" class="rounded img-fluid text-muted" alt="">
        {% else %}
        <video src="{{ attachment.file.url }}" class="img-fluid"></video>
        {% endif %}
    </div>
    {% endfor %}

    <div class="post-footer">
        <div class="likes" id="likes">
            {% if user.id in post.publicationlike_set.users_liked_list %}
            <img class="like-button"
                 data-src-other="{% static 'img/other/unliked.png' %}"
                 data-is-liked="1"
                 data-id="{{ post.id }}"
                 src="{% static 'img/other/liked.png' %}"
                 width="50" alt="like/unlike button">
            {% else %}
            <img class="like-button"
                 data-src-other="{% static 'img/other/liked.png' %}"
                 data-is-liked="0"
                 data-id="{{ post.id }}"
                 src="{% static 'img/other/unliked.png' %}"
                 width="50" alt="like/unlike button">
            {% endif %}
            <div><span class="like-count" id="like_count">{{ post.publicationlike_set.count }}</span></div>
        </div>
        <div class="comments mb-2">
            <div id="comment-list">
                {% for comment in post.comment_set.order_by_like_count %}
                <div class="comment">
                    <p style="font-style: italic">Комментарий от <a
                            href="{% url 'users:user_detail' user_id=comment.author.id %}">{{ comment.author.username }}</a>
                        {% if comment.responding_to %}
                        в ответ
                        <a href="{% url 'users:user_detail' user_id=comment.responding_to.author.id %}">{{ comment.responding_to.author.username }}</a>
                        "{{ comment.responding_to.text|truncatechars:10 }}"
                        {% endif %}
                        {# TODO: post deletion #}
                        {# <span class="float-end me-3">DEL</span>#}
                    </p>

                    <p class="comment-text">
                        <span>{{ comment.text }}</span>
                        <span class="float-end"><span>{{ comment.commentlike_set.count }}</span>
                                {% if user.id in comment.commentlike_set.users_liked_list %}
                                    <img class="comment-like-button"
                                         data-src-other="{% static 'img/other/unliked.png' %}"
                                         data-is-liked="1"
                                         data-id="{{ comment.id }}"
                                         src="{% static 'img/other/liked.png' %}"
                                         width="20" alt="like/unlike button">
                                {% else %}
                                    <img class="comment-like-button"
                                         data-src-other="{% static 'img/other/liked.png' %}"
                                         data-is-liked="0"
                                         data-id="{{ comment.id }}"
                                         src="{% static 'img/other/unliked.png' %}"
                                         width="20" alt="like/unlike button">
                                {% endif %}
                            </span>
                    </p>
                </div>
                {% empty %}
                <p id="no-comment-text" class="text-muted">оп, еще никто не оставлял комментарии здесь..</p>
                {% endfor %}
            </div>
            {% if user.is_authenticated %}
            <form class="row px-3 justify-content-between me-1" id="comment-form" data-id="{{ post.id }}">
                <label style="font-style: italic" class="mb-2" for="comment-input">Ваш комментарий</label>
                <input id="comment-input" type="text" class="form-control me-4 w-auto flex-grow-1 float-start"
                       placeholder="вау вот это пост!!">
                <input type="submit" class="btn btn-secondary w-auto float-end" value="Отправить!">
            </form>
            {% endif %}
        </div>
    </div>

</div>